#define PSI_ABILITY_ATTACK "Nex"
#define PSI_ABILITY_DEFENSE "Praesidium"
#define PSI_ABILITY_UTILITY "Auxilium"

#define INVOKE_PSI_MELEE	FLAG(0)
#define INVOKE_PSI_RANGED	FLAG(1)

#define INVOKE_PSI_ON_CLICK	(INVOKE_PSI_MELEE|INVOKE_PSI_RANGED)
