///////////////////////////////////////
// WARCRY SOUNDS IN VARIOUS LANGUAGES//
///////////////////////////////////////
// ZURICH ACCORD COMMON (ZAC)
GLOBAL_LIST_INIT(male_zac_warcries, list(
    'sound/voice/warcry/zac/male_zac_charge1.ogg',
    'sound/voice/warcry/zac/male_zac_charge2.ogg',
    'sound/voice/warcry/zac/male_zac_fourth1.ogg',
    'sound/voice/warcry/zac/male_zac_fourth2.ogg',
    'sound/voice/warcry/zac/male_zac_fourth3.ogg',
    'sound/voice/warcry/zac/male_zac_go1.ogg',
    'sound/voice/warcry/zac/male_zac_go2.ogg',
    'sound/voice/warcry/zac/male_zac_hooyah1.ogg' = 2,
    'sound/voice/warcry/zac/male_zac_hooyah2.ogg' = 2,
    'sound/voice/warcry/zac/male_zac_hooyah3.ogg' = 2,
    'sound/voice/warcry/zac/male_zac_indies1.ogg',
    'sound/voice/warcry/zac/male_zac_indies2.ogg',
    'sound/voice/warcry/zac/male_zac_indies3.ogg',
    'sound/voice/warcry/zac/male_zac_mars1.ogg',
    'sound/voice/warcry/zac/male_zac_mars2.ogg',
    'sound/voice/warcry/zac/male_zac_mars3.ogg',
    'sound/voice/warcry/zac/male_zac_mars4.ogg',
    'sound/voice/warcry/zac/male_zac_monty1.ogg',
    'sound/voice/warcry/zac/male_zac_monty2.ogg',
    'sound/voice/warcry/zac/male_zac_sol1.ogg',
    'sound/voice/warcry/zac/male_zac_sol2.ogg',
    'sound/voice/warcry/zac/male_zac_sol3.ogg',
))
GLOBAL_LIST_INIT(female_zac_warcries, list(
	'sound/voice/warcry/zac/female_zac_charge1.ogg',
	'sound/voice/warcry/zac/female_zac_charge2.ogg',
	'sound/voice/warcry/zac/female_zac_charge3.ogg',
	'sound/voice/warcry/zac/female_zac_charge4.ogg',
	'sound/voice/warcry/zac/female_zac_fourth1.ogg',
	'sound/voice/warcry/zac/female_zac_fourth2.ogg',
	'sound/voice/warcry/zac/female_zac_fourth3.ogg',
	'sound/voice/warcry/zac/female_zac_fourth4.ogg',
	'sound/voice/warcry/zac/female_zac_fourth5.ogg',
	'sound/voice/warcry/zac/female_zac_go1.ogg',
	'sound/voice/warcry/zac/female_zac_go2.ogg',
	'sound/voice/warcry/zac/female_zac_hooyah1.ogg' = 2,
	'sound/voice/warcry/zac/female_zac_hooyah2.ogg' = 2,
	'sound/voice/warcry/zac/female_zac_hooyah3.ogg' = 2,
	'sound/voice/warcry/zac/female_zac_hooyah4.ogg' = 2,
	'sound/voice/warcry/zac/female_zac_hooyah5.ogg' = 2,
	'sound/voice/warcry/zac/female_zac_indies1.ogg',
	'sound/voice/warcry/zac/female_zac_indies2.ogg',
	'sound/voice/warcry/zac/female_zac_indies3.ogg',
	'sound/voice/warcry/zac/female_zac_mars1.ogg',
	'sound/voice/warcry/zac/female_zac_mars2.ogg',
	'sound/voice/warcry/zac/female_zac_mars3.ogg',
	'sound/voice/warcry/zac/female_zac_monty1.ogg',
	'sound/voice/warcry/zac/female_zac_monty2.ogg',
	'sound/voice/warcry/zac/female_zac_sol1.ogg',
	'sound/voice/warcry/zac/female_zac_sol2.ogg',
))

// IBERIAN
GLOBAL_LIST_INIT(male_iberian_warcries, list(
	'sound/voice/warcry/iberian/male_iberian_cargar1.ogg' = 2,
	'sound/voice/warcry/iberian/male_iberian_cargar2.ogg' = 2,
	'sound/voice/warcry/iberian/male_iberian_cargar3.ogg' = 2,
	'sound/voice/warcry/iberian/male_iberian_gaia1.ogg',
	'sound/voice/warcry/iberian/male_iberian_gaia2.ogg', // Very funny
	'sound/voice/warcry/iberian/male_iberian_gaia3.ogg',
	'sound/voice/warcry/iberian/male_iberian_libertas1.ogg',
	'sound/voice/warcry/iberian/male_iberian_libertas2.ogg',
	'sound/voice/warcry/iberian/male_iberian_libertas3.ogg',
	'sound/voice/warcry/iberian/male_iberian_libertas4.ogg',
	'sound/voice/warcry/iberian/male_iberian_muerte1.ogg', // Whole fucking monologue
	'sound/voice/warcry/iberian/male_iberian_muerte2.ogg',
	'sound/voice/warcry/iberian/male_iberian_muerte3.ogg',
	'sound/voice/warcry/iberian/male_iberian_tyrannis1.ogg',
	'sound/voice/warcry/iberian/male_iberian_tyrannis2.ogg',
))
GLOBAL_LIST_INIT(female_iberian_warcries, list(
	'sound/voice/warcry/iberian/female_iberian_cargar1.ogg' = 2,
	'sound/voice/warcry/iberian/female_iberian_cargar2.ogg' = 2,
	'sound/voice/warcry/iberian/female_iberian_cargar3.ogg' = 2,
	'sound/voice/warcry/iberian/female_iberian_gaia1.ogg',
	'sound/voice/warcry/iberian/female_iberian_gaia2.ogg',
	'sound/voice/warcry/iberian/female_iberian_libertas1.ogg',
	'sound/voice/warcry/iberian/female_iberian_libertas2.ogg',
	'sound/voice/warcry/iberian/female_iberian_muerte1.ogg',
	'sound/voice/warcry/iberian/female_iberian_muerte2.ogg',
	'sound/voice/warcry/iberian/female_iberian_muerte3.ogg',
	'sound/voice/warcry/iberian/female_iberian_tyrannis1.ogg',
	'sound/voice/warcry/iberian/female_iberian_tyrannis2.ogg',
	'sound/voice/warcry/iberian/female_iberian_tyrannis3.ogg',
	'sound/voice/warcry/iberian/female_iberian_tyrannis4.ogg',
))

// PAN-SLAVIC
GLOBAL_LIST_INIT(male_panslavic_warcries, list(
	'sound/voice/warcry/panslavic/male_panslavic_gaia1.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_gaia2.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_gaia3.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_gaia4.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_god1.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_god2.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_god3.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_imperalism1.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_imperalism2.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_imperalism3.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_jurish1.ogg' = 2,
	'sound/voice/warcry/panslavic/male_panslavic_jurish2.ogg' = 2,
	'sound/voice/warcry/panslavic/male_panslavic_jurish3.ogg' = 2,
	'sound/voice/warcry/panslavic/male_panslavic_motherland1.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_motherland2.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_napred1.ogg' = 2,
	'sound/voice/warcry/panslavic/male_panslavic_napred2.ogg' = 2,
	'sound/voice/warcry/panslavic/male_panslavic_nasha1.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_nasha2.ogg',
	'sound/voice/warcry/panslavic/male_panslavic_nasha3.ogg',
))
GLOBAL_LIST_INIT(female_panslavic_warcries, list(
	'sound/voice/warcry/panslavic/female_panslavic_gaia1.ogg',
	'sound/voice/warcry/panslavic/female_panslavic_gaia2.ogg',
	'sound/voice/warcry/panslavic/female_panslavic_gaia3.ogg',
	'sound/voice/warcry/panslavic/female_panslavic_god1.ogg',
	'sound/voice/warcry/panslavic/female_panslavic_god2.ogg',
	'sound/voice/warcry/panslavic/female_panslavic_imperalism1.ogg',
	'sound/voice/warcry/panslavic/female_panslavic_imperalism2.ogg',
	'sound/voice/warcry/panslavic/female_panslavic_imperalism3.ogg',
	'sound/voice/warcry/panslavic/female_panslavic_jurish1.ogg' = 2,
	'sound/voice/warcry/panslavic/female_panslavic_jurish2.ogg' = 2,
	'sound/voice/warcry/panslavic/female_panslavic_motherland1.ogg',
	'sound/voice/warcry/panslavic/female_panslavic_motherland2.ogg',
	'sound/voice/warcry/panslavic/female_panslavic_motherland3.ogg',
	'sound/voice/warcry/panslavic/female_panslavic_napred1.ogg' = 2,
	'sound/voice/warcry/panslavic/female_panslavic_napred2.ogg' = 2,
	'sound/voice/warcry/panslavic/female_panslavic_nasha1.ogg',
	'sound/voice/warcry/panslavic/female_panslavic_nasha2.ogg',
))
