/obj/effect/cutscene_camera/s2ep2sc13
	camera_id = "Сцена 2-2 - Кадр 1"

/proc/fds2ep2_cutscene2()
	start_cutscene(/datum/modular_cutscene/s2ep2sc13)

/datum/modular_cutscene/s2ep2sc13/setup_actions(...)
	actions = list(
		ADD_SCREEN(/blackout/animated_better) = 4 SECONDS,
		REMOVE_SCREEN(/blackout/animated_better, 1 SECONDS),
		TP_CAMERA("Сцена 2-2 - Кадр 1"),
		MOVE_CAMERA(0, 3, 0, null),
		MOVE_CAMERA(0, 0, 10 SECONDS, SINE_EASING|EASE_IN),
		ADD_SCREEN(/cinema_borders),

		// Идут по тропинке

		MOVE_ACTOR(actor("Вильгельм - 2-2-1"), SOUTH),
		MOVE_ACTOR(actor("Амелия - 2-2-1"), SOUTH),
		PLAY_SOUND(sound('sound/effects/footstep/asteroid4.ogg', volume = 70)),

		MOVE_ACTOR(actor("Вильгельм - 2-2-1"), SOUTH) = 0.5 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid2.ogg', volume = 70)),
		MOVE_ACTOR(actor("Амелия - 2-2-1"), SOUTH),

		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Выглядишь неважно. Тяжёлый день?") = 1 SECONDS,

		PLAY_SOUND(sound('sound/effects/footstep/asteroid1.ogg', volume = 70)),
		MOVE_ACTOR(actor("Амелия - 2-2-1"), SOUTH) = 1 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid3.ogg', volume = 70)),
		MOVE_ACTOR(actor("Вильгельм - 2-2-1"), SOUTH),

		TALK_ACTOR(actor("Амелия - 2-2-1"), "Тяжёлая неделя.") = 4 SECONDS,
		TALK_ACTOR(actor("Амелия - 2-2-1"), "А вы что? Удивительно хорошо держитесь для кого-то в вашей кондиции."),
		TURN_ACTOR(actor("Амелия - 2-2-1"), EAST),

		PLAY_SOUND(sound('sound/effects/footstep/asteroid2.ogg', volume = 70)),
		MOVE_ACTOR(actor("Вильгельм - 2-2-1"), SOUTH) = 0.2 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid5.ogg', volume = 70)),
		MOVE_ACTOR(actor("Амелия - 2-2-1"), SOUTH) = 3 SECONDS,

		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Дело навыка..."),
		TURN_ACTOR(actor("Вильгельм - 2-2-1"), SOUTH) = 2 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Вообще-то, я должен поблагодарить плешивую за то, что я в принципе \"держусь\"."),
		PLAY_SOUND(sound('sound/effects/footstep/asteroid1.ogg', volume = 70)),
		MOVE_ACTOR(actor("Вильгельм - 2-2-1"), SOUTH) = 1 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid4.ogg', volume = 70)),
		MOVE_ACTOR(actor("Амелия - 2-2-1"), SOUTH) = 3 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Я ведь вполне мог сыграть в ящик и раньше.") = 2 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid5.ogg', volume = 70)),
		MOVE_ACTOR(actor("Амелия - 2-2-1"), SOUTH) = 2 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid3.ogg', volume = 70)),
		MOVE_ACTOR(actor("Вильгельм - 2-2-1"), SOUTH),
		TURN_ACTOR(actor("Амелия - 2-2-1"), SOUTH),
		TALK_ACTOR(actor("Амелия - 2-2-1"), "Не уверена, что такая жизнь далеко ушла от Ада.") = 6 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Аргумент принимается. Но я бы скорее сравнил её с Чистилищем.") = 2 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid5.ogg', volume = 70)),
		MOVE_ACTOR(actor("Амелия - 2-2-1"), SOUTH),
		MOVE_ACTOR(actor("Вильгельм - 2-2-1"), SOUTH),
		PLAY_SOUND(sound('packs/infinity/sound/voice/giggle_female_2.ogg', volume = 20)),
		PLAY_SOUND(sound('mods/emote_panel/sound/laugh_male_2.ogg', volume = 20)),
		TALK_ACTOR(actor("Амелия - 2-2-1"), "!рассмеялась."),
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "!рассмеялся.") = 4 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Редко когда человеку доводится второй шанс исправить ошибки всей его жизни.") = 2 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "!приподнимает голову к небу, вздыхая."),

		// Амелия что-то замечает
		PLAY_SOUND(sound('sound/effects/footstep/asteroid1.ogg', volume = 70)),
		MOVE_ACTOR(actor("Амелия - 2-2-1"), SOUTH) = 2 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid3.ogg', volume = 70)),
		MOVE_ACTOR(actor("Вильгельм - 2-2-1"), SOUTH),
		TALK_ACTOR(actor("Амелия - 2-2-1"), "!повела ухом."),
		TURN_ACTOR(actor("Амелия - 2-2-1"), WEST) = 4 SECONDS,

		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Может быть, времени у меня и немного, но нежели опускать руки...") = 2 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid2.ogg', volume = 70)),
		MOVE_ACTOR(actor("Вильгельм - 2-2-1"), SOUTH),

		// Амелия останавливается
		CHANGE_ACTOR_VISUALS(actor("Амелия - 2-2-1"), "EP2 PAGE 2 - 2") = 2 SECONDS,

		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Лучше провести его с пользой, не думаешь?"),
		PLAY_SOUND(sound('sound/effects/footstep/asteroid5.ogg', volume = 70)),
		MOVE_ACTOR(actor("Вильгельм - 2-2-1"), SOUTH),
		TURN_ACTOR(actor("Вильгельм - 2-2-1"), WEST) = 2 SECONDS,
		CHANGE_ACTOR_VISUALS(actor("Вильгельм - 2-2-1"), "Current Alt") = 0.5 SECONDS,
		TURN_ACTOR(actor("Вильгельм - 2-2-1"), NORTH) = 0.5 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Амелия?") = 4 SECONDS,
		PLAY_SOUND(sound('sound/weapons/Egloves.ogg', volume = 70)),
		MOVE_ACTOR(actor("Снаряд - 1"), EAST),
		CHANGE_ACTOR_MATRIX(actor("Снаряд - 1"), 90, 0.1 SECONDS, SINE_EASING, null) = 0.1 SECONDS,
		TALK_ACTOR(actor("Амелия - 2-2-1"), "За нами кто-то сле-...!"),

		// Первый выстрел
		MOVE_ACTOR(actor("Снаряд - 1"), EAST),
		CHANGE_ACTOR_MATRIX(actor("Снаряд - 1"), 90, 0.1 SECONDS, SINE_EASING, null) = 0.1 SECONDS,
		MOVE_ACTOR(actor("Снаряд - 1"), EAST),
		CHANGE_ACTOR_MATRIX(actor("Снаряд - 1"), 90, 0.1 SECONDS, SINE_EASING, null) = 0.1 SECONDS,
		MOVE_ACTOR(actor("Снаряд - 1"), EAST),
		CHANGE_ACTOR_MATRIX(actor("Снаряд - 1"), 90, 0.1 SECONDS, SINE_EASING, null) = 0.1 SECONDS,
		MOVE_ACTOR(actor("Снаряд - 1"), EAST),
		CHANGE_ACTOR_MATRIX(actor("Снаряд - 1"), 90, 0.1 SECONDS, SINE_EASING, null) = 0.1 SECONDS,
		CHANGE_ACTOR_VISIBILITY(actor("Снаряд - 1"), 0, 0.2 SECONDS, SINE_EASING, null),
		CHANGE_ACTOR_VISIBILITY(actor("Сетка"), 255, 0.2 SECONDS, SINE_EASING, ANIMATION_PARALLEL),
		CHANGE_ACTOR_MATRIX(actor("Амелия - 2-2-1"), 90, 0.2 SECONDS, SINE_EASING, ANIMATION_PARALLEL),
		SHIFT_ACTOR(actor("Амелия - 2-2-1"), 32, 0, 0.4 SECONDS, SINE_EASING|EASE_OUT, ANIMATION_PARALLEL),
		SHIFT_ACTOR(actor("Сетка"), 32, 0, 0.4 SECONDS, SINE_EASING|EASE_OUT, ANIMATION_PARALLEL),
		CHANGE_ACTOR_VISUALS(actor("Амелия - 2-2-1"), "EP2 PAGE 2 - 3") = 2 SECONDS,

		// Реакция
		TALK_ACTOR(actor("Амелия - 2-2-1"), "!безуспешно ёрзает."),
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Срань!"),

		// Второй снаряд
		PLAY_SOUND(sound('sound/weapons/Taser.ogg', volume = 70)),
		MOVE_ACTOR(actor("Снаряд - 2"), NORTH) = 0.1 SECONDS,
		MOVE_ACTOR(actor("Снаряд - 2"), NORTH) = 0.1 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid4.ogg', volume = 70)),
		MOVE_ACTOR(actor("Вильгельм - 2-2-1"), NORTH),
		MOVE_ACTOR(actor("Снаряд - 2"), NORTH) = 0.1 SECONDS,
		MOVE_ACTOR(actor("Снаряд - 2"), NORTH) = 0.1 SECONDS,
		MOVE_ACTOR(actor("Снаряд - 2"), NORTH) = 0.1 SECONDS,
		TURN_ACTOR(actor("Амелия - 2-2-1"), EAST),
		CHANGE_ACTOR_VISIBILITY(actor("Снаряд - 2"), 0, 0.2 SECONDS, SINE_EASING, null),
		CHANGE_ACTOR_VISIBILITY(actor("Разряд"), 255, 0.1 SECONDS, SINE_EASING, null) = 0.5 SECONDS,
		CHANGE_ACTOR_VISIBILITY(actor("Разряд"), 0, 0.1 SECONDS, SINE_EASING, null),
		PLAY_SOUND(sound('sound/effects/footstep/asteroid2.ogg', volume = 70)),
		MOVE_ACTOR(actor("Партизан 4 - 2-2-1"), WEST),
		MOVE_ACTOR(actor("Партизан 3 - 2-2-1"), EAST),
		MOVE_ACTOR(actor("Вильгельм - 2-2-1"), NORTH),
		MOVE_ACTOR(actor("Разряд"), NORTH),
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "!припадает на одно колено."),
		CHANGE_ACTOR_MATRIX(actor("Вильгельм - 2-2-1"), 10, 0.3 SECONDS, SINE_EASING, ANIMATION_PARALLEL) = 2 SECONDS,

		// Окружают
		PLAY_SOUND(sound('sound/effects/footstep/asteroid4.ogg', volume = 70)),
		MOVE_ACTOR(actor("Партизан 1 - 2-2-1"), EAST),
		MOVE_ACTOR(actor("Партизан 2 - 2-2-1"), NORTH),
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "!откашливается.") = 1 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid1.ogg', volume = 70)),
		MOVE_ACTOR(actor("Партизан 4 - 2-2-1"), WEST),
		MOVE_ACTOR(actor("Партизан 2 - 2-2-1"), NORTH),
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Живая?") = 2 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid5.ogg', volume = 70)),
		MOVE_ACTOR(actor("Партизан 3 - 2-2-1"), EAST),
		MOVE_ACTOR(actor("Партизан 2 - 2-2-1"), NORTH),
		TALK_ACTOR(actor("Амелия - 2-2-1"), "Б-бывало и лучше-") = 2 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid5.ogg', volume = 70)),
		MOVE_ACTOR(actor("Партизан 2 - 2-2-1"), NORTH) = 2 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid1.ogg', volume = 70)),
		MOVE_ACTOR(actor("Партизан 1 - 2-2-1"), EAST),
		CHANGE_ACTOR_MATRIX(actor("Вильгельм - 2-2-1"), 0, 2 SECONDS, SINE_EASING, null),
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "...держись там, котёнок.") = 1 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid4.ogg', volume = 70)),
		MOVE_ACTOR(actor("Партизан 4 - 2-2-1"), WEST),
		CHANGE_ACTOR_VISUALS(actor("Вильгельм - 2-2-1"), "EP2 PAGE 2 - 1") = 2 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid3.ogg', volume = 70)),
		MOVE_ACTOR(actor("Партизан 4 - 2-2-1"), WEST),
		MOVE_ACTOR(actor("Партизан 1 - 2-2-1"), EAST),
		TALK_ACTOR(actor("Партизан 2 - 2-2-1"), "Не шевелись.") = 2 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "А то что?") = 2 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Если вы нас гасить собрались - к чему прелюдия?") = 4 SECONDS,
		TALK_ACTOR(actor("Партизан 2 - 2-2-1"), "Продолжишь вякать, и я быстро проделаю пару дыр в твоей треуголке.") = 2 SECONDS,
		CHANGE_ACTOR_VISIBILITY(actor("Райфлер - 2-2-1"), 255, 0, null, null),
		PLAY_SOUND(sound('sound/effects/footstep/asteroid2.ogg', volume = 70)),
		MOVE_ACTOR(actor("Райфлер - 2-2-1"), SOUTH),
		CHANGE_ACTOR_VISUALS(actor("Вильгельм - 2-2-1"), "Current Alt"),
		TURN_ACTOR(actor("Амелия - 2-2-1"), NORTH) = 4 SECONDS,
		TALK_ACTOR(actor("Партизан 2 - 2-2-1"), "В вашем распоряжении, капитан.") = 2 SECONDS,
		TALK_ACTOR(actor("Райфлер - 2-2-1"), "!медленно кивает, взводя курок.") = 4 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid3.ogg', volume = 70)),
		MOVE_ACTOR(actor("Райфлер - 2-2-1"), SOUTH),
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Ошибку понял. Может поговорим?") = 4 SECONDS,
		TURN_ACTOR(actor("Амелия - 2-2-1"), EAST),
		TALK_ACTOR(actor("Амелия - 2-2-1"), "...серьёзно?") = 2 SECONDS,

		// Допрос
		TALK_ACTOR(actor("Райфлер - 2-2-1"), "Откуда у тебя эта броня?") = 6 SECONDS,
		TURN_ACTOR(actor("Амелия - 2-2-1"), NORTH),
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Я её... владелец?") = 4 SECONDS,
		TALK_ACTOR(actor("Райфлер - 2-2-1"), "Ложь.") = 2 SECONDS,
		TURN_ACTOR(actor("Партизан 4 - 2-2-1"), SOUTH),
		TALK_ACTOR(actor("Райфлер - 2-2-1"), "Что случилось с тем, кому эта броня принадлежала?") = 6 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Говорю же - она МОЯ. С чего вы вообще решили, что она должна принадлежать кому-либо ещё!?") = 6 SECONDS,
		TALK_ACTOR(actor("Райфлер - 2-2-1"), "!хмурится.") = 2 SECONDS,
		TALK_ACTOR(actor("Райфлер - 2-2-1"), "Потому что её владелец мне отлично знаком.") = 4 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid1.ogg', volume = 70)),
		MOVE_ACTOR(actor("Райфлер - 2-2-1"), SOUTH),
		TALK_ACTOR(actor("Райфлер - 2-2-1"), "А ты на него не то что не похож - ты просто позоришь его имя.") = 4 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Ты что, говоришь про-...") = 2 SECONDS,
		TALK_ACTOR(actor("Райфлер - 2-2-1"), "Покажите мне морду этого урода. И чтоб без фокусов.") = 4 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid5.ogg', volume = 70)),
		MOVE_ACTOR(actor("Партизан 2 - 2-2-1"), NORTH) = 2 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid1.ogg', volume = 70)),
		MOVE_ACTOR(actor("Партизан 4 - 2-2-1"), WEST),
		TALK_ACTOR(actor("Райфлер - 2-2-1"), "С девчёнки тоже глаз не спускайте.") = 2 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid2.ogg', volume = 70)),
		MOVE_ACTOR(actor("Партизан 1 - 2-2-1"), EAST),
		TURN_ACTOR(actor("Партизан 1 - 2-2-1"), EAST),
		TALK_ACTOR(actor("Партизан 2 - 2-2-1"), "!хватает мужчину за голову, сдёргивая шлем."),
		PLAY_SOUND(sound('sound/effects/rustle4.ogg', volume = 100)),
		CHANGE_ACTOR_VISUALS(actor("Вильгельм - 2-2-1"), "EP2 PAGE 2 - 2"),
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "!ворчит.") = 2 SECONDS,
		PLAY_SOUND(sound('sound/effects/footstep/asteroid2.ogg', volume = 70)),
		MOVE_ACTOR(actor("Партизан 2 - 2-2-1"), SOUTH) = 4 SECONDS,
		TURN_ACTOR(actor("Вильгельм - 2-2-1"), EAST),
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Ну? И чего встали? Шрамы украшают мужчину, знаете ли.") = 2 SECONDS,
		TALK_ACTOR(actor("Райфлер - 2-2-1"), "Какого...") = 2 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Меня вся эта херня начинает утомлять...") = 6 SECONDS,
		PLAY_SOUND(sound('maps/torch_doh/cutscenes/sounds/Tears.mp3', volume = 10)),
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Увидели что хотели!?"),
		TURN_ACTOR(actor("Вильгельм - 2-2-1"), NORTH) = 4 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Может, теперь расскажете кто вы такие?") = 3 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Или ДНК моё ещё возьмё-...") = 1 SECONDS,
		PLAY_SOUND(sound('sound/effects/internals.ogg', volume = 70)),
		PLAY_SOUND(sound('sound/items/helmet_open.ogg', volume = 100)),
		TALK_ACTOR(actor("Райфлер - 2-2-1"), "!опускает револьвер, щёлкая рычажком на шее.") = 2 SECONDS,
		CHANGE_ACTOR_VISUALS(actor("Райфлер - 2-2-1"), "Leader 5") = 4 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "...-те.") = 6 SECONDS,
		TALK_ACTOR(actor("Вильгельм - 2-2-1"), "Крис?...") = 2 SECONDS,
		ADD_SCREEN(/blackout/animated_better) = 4 SECONDS,
		RETURN_VIEWERS
	)
