/obj/vehicles
	// ENGINE SOUND
	var/datum/sound_token/working_sound_token //autogenerated, don't touch unless you know what you're doing
	var/working_sound_id //same as above

	var/list/working_sounds = list('mods/_fd/multitile_vehicles/sounds/working.ogg')
	var/working_volume = 50

	var/startup_sound = 'mods/_fd/multitile_vehicles/sounds/startup.ogg'
	var/shutdown_sound = 'mods/_fd/multitile_vehicles/sounds/shutdown.ogg'
	var/startup_volume = 50
	var/shutdown_volume = 50
	var/startup_length = 4 SECONDS

	// ALARM SOUNDS
	var/has_alarm = FALSE
	var/datum/sound_token/alarm_sound_token //autogenerated, don't touch unless you know what you're doing
	var/alarm_sound_id //same as above

	var/list/alarm_sounds = list('mods/_fd/multitile_vehicles/sounds/alarm.ogg')
	var/alarm_volume = 150

	// SOUND EFFECTS
	var/list/move_sound = list('mods/_fd/multitile_vehicles/sounds/move.ogg')
	var/list/brake_sound = list('mods/_fd/multitile_vehicles/sounds/brake.ogg')
	var/list/crash_sound = list('mods/_fd/multitile_vehicles/sounds/crash.ogg')
	var/list/honk_sound = list('mods/_fd/multitile_vehicles/sounds/honk.ogg')
	var/list/enter_sound = list('mods/_fd/multitile_vehicles/sounds/enter.ogg')
	var/move_volume = 50
	var/brake_volume = 50
	var/crash_volume = 100
	var/honk_volume = 150
	var/enter_volume = 50

// ENGINE SOUNDS
/obj/vehicles/proc/play_working_soundloop()
	if(!working_sounds)
		return
	if(!working_sound_token)
		if(startup_sound)
			playsound(src, startup_sound, (startup_volume), FALSE)
			addtimer(new Callback(src, PROC_REF(assign_working_sound_token)), startup_length)
		else
			assign_working_sound_token()

/obj/vehicles/proc/assign_working_sound_token()
	if(!working_sound_id)
		working_sound_id = "[type]_[sequential_id(type)]"
	working_sound_token = GLOB.sound_player.PlayLoopingSound(src, working_sound_id, pick(working_sounds), working_volume, 10, 1)
	working_sound_token.SetVolume(working_volume)

/obj/vehicles/proc/stop_working_soundloop()
	if(working_sound_token)
		QDEL_NULL(working_sound_token)
		if(shutdown_sound)
			playsound(src, shutdown_sound, (shutdown_volume), FALSE)

// ALARM SOUNDS
/obj/vehicles/verb/toggle_alarm()
	set name = "Toggle Alarm"
	set category = "Vehicle"
	set src in view(1)
	if(health_dead)
		return
	var/mob/living/user = usr
	if(!has_alarm)
		to_chat(user, SPAN_WARNING("This vehicle does not have an alarm system."))
		return
	if(!istype(user) || !(user in get_occupants_in_position(dashboard_control_positions)))
		to_chat(user, SPAN_NOTICE("You must have access to dashboard of \the [src] to toggle the alarm."))
		return

	if(alarm_sound_token)
		to_chat(user,SPAN_NOTICE("You toggle [src]'s alarm off."))
		stop_alarm_soundloop()
	else
		to_chat(user,SPAN_NOTICE("You toggle [src]'s alarm on."))
		play_alarm_sound()

/obj/vehicles/proc/play_alarm_sound()
	if(!alarm_sounds)
		return
	if(!alarm_sound_token)
		assign_alarm_sound_token()

/obj/vehicles/proc/assign_alarm_sound_token()
	if(!alarm_sound_id)
		alarm_sound_id = "[type]_[sequential_id(type)]"
	alarm_sound_token = GLOB.sound_player.PlayLoopingSound(src, alarm_sound_id, pick(alarm_sounds), alarm_volume, 20, 1)
	alarm_sound_token.SetVolume(alarm_volume)

/obj/vehicles/proc/stop_alarm_soundloop()
	if(alarm_sound_token)
		QDEL_NULL(alarm_sound_token)

// SOUND EFFECTS
/obj/vehicles/proc/play_move_sound()
	playsound(src, (pick(move_sound)), (move_volume), TRUE)

/obj/vehicles/proc/play_brake_sound()
	playsound(src, (pick(brake_sound)), (brake_volume), TRUE)

/obj/vehicles/proc/play_crash_sound()
	playsound(src, (pick(crash_sound)), (crash_volume), TRUE)

/obj/vehicles/proc/play_honk_sound()
	playsound(src, (pick(honk_sound)), (honk_volume), TRUE)

/obj/vehicles/proc/play_enter_sound()
	playsound(src, (pick(enter_sound)), (enter_volume), TRUE)
