/obj/vehicles
	var/datum/sound_token/working_sound_token //autogenerated, don't touch unless you know what you're doing
	var/working_sound_id //same as above

	var/list/working_sounds = list('mods/_fd/multitile_vehicles/sounds/working.ogg')
	var/working_volume = 25

	var/list/move_sound = list('mods/_fd/multitile_vehicles/sounds/move.ogg')
	var/list/crash_sound = list('mods/_fd/multitile_vehicles/sounds/crash.ogg')
	var/move_volume = 20
	var/crash_volume = 30

	var/startup_sound = 'mods/_fd/multitile_vehicles/sounds/startup.ogg'
	var/shutdown_sound = 'mods/_fd/multitile_vehicles/sounds/shutdown.ogg'
	var/startup_volume = 30
	var/shutdown_volume = 25
	var/startup_length = 4 SECONDS

/obj/vehicles/proc/play_working_soundloop()
	if(!working_sounds)
		return
	if(!working_sound_token)
		if(startup_sound)
			playsound(src, startup_sound, (startup_volume), FALSE)
			addtimer(new Callback(src, PROC_REF(assign_working_sound_token)), startup_length)
		else
			assign_working_sound_token()

/obj/vehicles/proc/assign_working_sound_token()
	if(!working_sound_id)
		working_sound_id = "[type]_[sequential_id(type)]"
	working_sound_token = GLOB.sound_player.PlayLoopingSound(src, working_sound_id, pick(working_sounds), working_volume, 10, 1)
	working_sound_token.SetVolume(working_volume)

/obj/vehicles/proc/stop_working_soundloop()
	if(working_sound_token)
		QDEL_NULL(working_sound_token)
		if(shutdown_sound)
			playsound(src, shutdown_sound, (shutdown_volume), FALSE)

/obj/vehicles/proc/play_move_sound()
	playsound(src, (pick(move_sound)), (move_volume), TRUE)

/obj/vehicles/proc/play_crash_sound()
	playsound(src, (pick(crash_sound)), (crash_volume), TRUE)
